"PLAYER" : 3
"HipPitch" : 11
animations :
    motion:
      torjubel : "gruss2"

# Achtung: keine virtuellen Motoren in die Motorliste schreiben! (30 momentan)
motors: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 25, 26, 27, 28, 29]

"RobotTypeName": "Hambot"
