#!/bin/bash

#für die nicht optimierte Variante nur einen Durchlauf
touch tt.o
make clean test -e CC='g++' >/dev/null 2>&1
echo "1 0"| ./test
gprof test > robotvision_analyse_mit_O0
for i in {1..3}
do
    make clean test -e CC='g++' OO=O${i} >/dev/null 2>&1
    #gönne den optimierten Versionen ein paar mehr Durchläufe
    echo "100 0"| ./test
    gprof test > robotvision_analyse_mit_O${i}
done
