#Werte erstellt durch 3doerfle, 3bimberg, 3windsor (Praktikum sose 2015)
"Darwin":

  #Grenzwerte müssen auf härterem boden auch härter eingestellt werden,
  #dies erfolgt mit dem boden_koeffizient
  "boden_koeffizient": 1.25   #WEICH(kunstrasen Spielfeld)= 1.0 , HART(teppich Spielfeld)= 1.25

  #Grenzwerte schärfer --> fruehere Reaktion aber haeufigere Fehlinterpretation, zb. beim Laufen
  #Grenzwerte sanfter --> zu spaete Raktion
  "grenzwert_gyro_y_vorne":  -50.0 # > gyroY
  "grenzwert_gyro_y_hinten":  50.0 # < gyroY
  "grenzwert_gyro_x_rechts": -30.0 # > gyroX
  "grenzwert_gyro_x_links":   30.0 # < gyroX

  #Es wird genau über die ersten 20 Motoren iteriert
  "motor_stellungen_vorne":  [-145.0, 145.0, -10.0, 10.0, -25.0, 25.0, 0.0, 0.0, 30.0, -30.0, 30.0, -30.0, 95.0, -95.0, 90.0, -90.0, -20.0, 20.0, 0.0, 20.0]
  "motor_stellungen_hinten": [60.0, -60.0, 0.0, 0.0, -20.0, 20.0, 17.0, -17.0, 0.0, 0.0, -110.0, 110.0, 100.0, -100.0, 0.0, 0.0, 0.0, 0.0, 0.0, -40.0]
  "motor_stellungen_rechts": [-145.0, 170.0, -10.0, -40.0, -25.0, 60.0, 0.0, 0.0, 30.0, -50.0, 30.0, -30.0, 95.0, 0.0, 90.0, -90.0, -20.0, 20.0, 0.0, 20.0]
  "motor_stellungen_links":  [-170.0, 145.0, 40.0, 10.0, -60.0, 25.0, 0.0, 0.0, 50.0, -30.0, 30.0, -30.0, 0.0, -95.0, 90.0, -90.0, -20.0, 20.0, 0.0, 20.0]

  #false = motoren werden bei fallerkennung abgeschaltet
  "dynamisches_fallen_aktiviert": true


"Hambot": #Achtung werte nur kopiert und nicht getestet!!!

  #Koeffizient wird auch benutzt wenn fallen deaktiviert --> nur dass er die motoren ausmacht
  "boden_koeffizient": 1.25 #--> wert ist gut für HAMBOT, da dieser Wert das laufen nicht beeinträchtigt

  "grenzwert_gyro_y_vorne":  -22 # > gyroY
  "grenzwert_gyro_y_hinten":  22 # < gyroY
  "grenzwert_gyro_x_rechts": -30 # > gyroX
  "grenzwert_gyro_x_links":   30 # < gyroX

  "motor_stellungen_vorne":  [-145.0, 145.0, -10.0, 10.0, -25.0, 25.0, 0.0, 0.0, 30.0, -30.0, 30.0, -30.0, 95.0, -95.0, 90.0, -90.0, -20.0, 20.0, 0.0, 20.0]
  "motor_stellungen_hinten": [60.0, -60.0, -30.0, 30.0, 45.0, -45.0, 17.0, -17.0, 0.0, 0.0, -110.0, 110.0, 110.0, -110.0, 0.0, 0.0, 0.0, 0.0, 0.0, -40.0]
  "motor_stellungen_rechts": [-145.0, 145.0, -10.0, 10.0, -25.0, 25.0, 0.0, 0.0, 30.0, -30.0, 30.0, -30.0, 95.0, -95.0, 90.0, -90.0, -20.0, 20.0, 0.0, 20.0]
  "motor_stellungen_links": [-145.0, 145.0, -10.0, 10.0, -25.0, 25.0, 0.0, 0.0, 30.0, -30.0, 30.0, -30.0, 95.0, -95.0, 90.0, -90.0, -20.0, 20.0, 0.0, 20.0]

  #DEAKTIVIERT lassen, stellungen wurden noch nicht für ihn getestet
  "dynamisches_fallen_aktiviert": false

"Minibot":

  #Grenzwerte müssen auf härterem boden auch härter eingestellt werden,
  #dies erfolgt mit dem boden_koeffizient
  "boden_koeffizient": 1.25   #WEICH(kunstrasen Spielfeld)= 1.0 , HART(teppich Spielfeld)= 1.25

  #Grenzwerte schärfer --> fruehere Reaktion aber haeufigere Fehlinterpretation, zb. beim Laufen
  #Grenzwerte sanfter --> zu spaete Raktion
  "grenzwert_gyro_y_vorne":  -50.0 # > gyroY
  "grenzwert_gyro_y_hinten":  50.0 # < gyroY
  "grenzwert_gyro_x_rechts": -30.0 # > gyroX
  "grenzwert_gyro_x_links":   30.0 # < gyroX

  #Es wird genau über die ersten 20 Motoren iteriert
  "motor_stellungen_vorne":  [-145.0, 145.0, -10.0, 10.0, -25.0, 25.0, 0.0, 0.0, 30.0, -30.0, 30.0, -30.0, 95.0, -95.0, 90.0, -90.0, -20.0, 20.0, 0.0, 20.0]
  "motor_stellungen_hinten": [60.0, -60.0, 0.0, 0.0, -20.0, 20.0, 17.0, -17.0, 0.0, 0.0, -110.0, 110.0, 100.0, -100.0, 0.0, 0.0, 0.0, 0.0, 0.0, -40.0]
  "motor_stellungen_rechts": [-145.0, 170.0, -10.0, -40.0, -25.0, 60.0, 0.0, 0.0, 30.0, -50.0, 30.0, -30.0, 95.0, 0.0, 90.0, -90.0, -20.0, 20.0, 0.0, 20.0]
  "motor_stellungen_links":  [-170.0, 145.0, 40.0, 10.0, -60.0, 25.0, 0.0, 0.0, 50.0, -30.0, 30.0, -30.0, 0.0, -95.0, 90.0, -90.0, -20.0, 20.0, 0.0, 20.0]

  #false = motoren werden bei fallerkennung abgeschaltet
  "dynamisches_fallen_aktiviert": true



