motors: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 27, 28, 29, 30]
foot_size: [[110, -70], [94, -36]]
min_joint_id: 0
max_joint_id: 30
Root:
    name: "Root"
    id: 0
    transform: [0, 0, 0]
    rpy: [0, 0, 0]
    "comment": "The \"Virtual\" Root lies inside the ratation axis of the shoulder pitches"
    mass_offsets:
        #Body: {mass: 1326.0, offset: [-30, 3, -55 - 15] }
        Body: {mass: 1326.0, offset: [-30, 3, -70] }
        ZweiDrittelKamerakabel: {mass: 6.666, offset: [0, 0, 0] }
    #,def_min_max_angles: [0, 0, 0]
ChainNames: ["Head","RArm","LArm","RLeg","LLeg"]
Head:
    - name: "Neck"
      id: 19
      transform: [0, 0, 43]
      rpy: [90, 180, 0]
      comment: "Due to the Joint Rotation, the x-axis is the negative global x-axis"
      mass_offsets:
        Beispielmasse: {mass: 0.0, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "Head"
      id: 20
      transform: [0, 50.5, 0]
      rpy: [-90, -90, 0]
      mass_offsets:
        Kamera19_20Drehhalter: {mass: 12.0, offset: [-28, 0, 0.5] }
        #Kamera19_20Drehhalter: {mass: 12.0, offset: [0.5, 7 + 18 + 3, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "CameraHolder"
      id: 36
      transform: [42, 0, -17]
      rpy: [180, 90, 0]
      comment: "The local and global coordinate system are equal"
      mass_offsets:
        Motor: {mass: 76.0, offset: [10, 0, -37] }
        #MetallKrams: {mass: 166 - 76 - 52.0, offset: [-20, 0, 5] }
        MetallKrams: {mass: 38.0, offset: [-2, 0, -20] }
        Kamera: {mass: 42.0, offset: [-2, 0, -20] }
        DrittelKamerakabel: {mass: 3.334, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, 0, 0]
    - name: "Camera"
      id: 31
      transform: [0, 0, 0]
      rpy: [0, -13.0, 0]
      comment: "'Virtual Joint', because the Camera is adjusted with a little angle"
      mass_offsets:
        Beispielmasse: {mass: 0.0, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, 0, 0]

RArm:
    - name: "RShoulderPitch"
      id: 1
      transform: [0, -96, 0]
      rpy: [180, 0, 0]
      comment: "x-axis in direction of global x-axis"
      mass_offsets:
        Motor: {mass: 76.0, offset: [-5, 0, 0] }
        Motorkabel: {mass: 6.0, offset: [0, 0, 0] }
        Motorhalterung: {mass: 6.0, offset: [0, 0, 15] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RShoulderRoll"
      id: 3
      transform: [0, 45, 20]
      rpy: [-135, 180, -90]
      comment: "y-axis in direction of negative global x-axis"
      mass_offsets:
        MetallverbindugsstückPitchRoll: {mass: 12.0, offset: [-15, 0, 2] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RElbow"
      id: 5
      transform: [190, 0, 0]
      rpy: [-90, 0, 0]
      mass_offsets:
        KomplettVerbindugsStückGemitteltesCoG: {mass: 196.0, offset: [0, 0, -60] }
        ShoulderRollMotor: {mass: 0.0, offset: [0, 0, 0] }
        ElbowMotor: {mass: 0.0, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RArmEndpoint"
      id: 32
      transform: [188, 0, 0]
      rpy: [-90, -45, 90]
      mass_offsets:
        ArmEndstückHalterung: {mass: 12.0, offset: [-187.5, -6, -6] }
        #ArmEndMetallStückLang: {mass: 38.5, offset: [175 / 2 + 25.0, -12.5, -15] }
        ArmEndMetallStückLang: {mass: 38.5, offset: [-87.5, -20, 0] }
        ArmEndMetallStückHalterung: {mass: 5.5, offset: [-175, -8.8, -8.8] }
      #,def_min_max_angles: [0, 0, 0]

LArm:
    - name: "LShoulderPitch"
      id: 2
      transform: [0, 96, 0]
      rpy: [0, 0, 0]
      comment: "the x-axis is in direction of the global x-axis"
      mass_offsets:
        Motor: {mass: 76.0, offset: [-5, 0, 0] }
        Motorkabel: {mass: 6.0, offset: [0, 0, 0] }
        Motorhalterung: {mass: 6.0, offset: [0, 0, -15] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LShoulderRoll"
      id: 4
      transform: [0, 45, -20]
      rpy: [-45, 0, 90]
      comment: "y-axis in direction of negative global x-axis"
      mass_offsets:
        MetallverbindugsstückPitchRoll: {mass: 12.0, offset: [-15, 0, -2] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LElbow"
      id: 6
      transform: [190, 0, 0]
      rpy: [-90, 0, 0]
      mass_offsets:
        KomplettVerbindugsStückGemitteltesCoG: {mass: 196.0, offset: [0, 0, 60] }
        ShoulderRollMotor: {mass: 0.0, offset: [0, 0, 0] }
        ElbowMotor: {mass: 0.0, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LArmEndpoint"
      id: 33
      transform: [188, 0, 0]
      rpy: [-90, -135, 90]
      mass_offsets:
        ArmEndstückHalterung: {mass: 12.0, offset: [-187.5, 8.8, -8.8] }
        #ArmEndMetallStückLang: {mass: 38.5, offset: [175 / 2 + 25.0, -12.5, 15] }
        ArmEndMetallStückLang: {mass: 38.5, offset: [-87.5, 20, 0] }
        ArmEndMetallStückHalterung: {mass: 5.5, offset: [-175, 8.8, -8.8] }
      #,def_min_max_angles: [0, 0, 0]

RLeg:
    - name: "BellyRoll"
      id: 29
      transform: [0, 0, -237]
      rpy: [90, 0, -90]
      comment: "Using virtual bellyPitch, it's adjusted like the left one'"
      mass_offsets:
        Beispielmasse: {mass: 0.0, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "BellyPitch"
      id: 30
      transform: [15, 0, 0]
      rpy: [90, 0, 0]
      comment: ""
      mass_offsets:
        BellyPitch_RollHalterung: {mass: 34.0, offset: [35, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RHipYaw"
      id: 7
      transform: [60, 60, 0]
      rpy: [90, 0, -90]
      comment: "the x-axis is direction of global x-axis"
      mass_offsets:
        #HalbeBellyRollHipPitchKonstruktion: {mass: (338 - 140) / 2.0, offset: [-35, 0, 0] }
        HalbeBellyRollHipPitchKonstruktion: {mass: 99.0, offset: [0, -45, 0] }
        #HalberMX64Anteil: {mass: 140 / 2.0, offset: [-15, 0, 0] }
        HalberMX64Anteil: {mass: 70.0, offset: [-65, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RHipRoll"
      id: 9
      transform: [0, 0, 0]
      rpy: [0, 0, 90]
      comment: "the local x-axis is the negativ global z-axis"
      mass_offsets:
        VerbindugsstückHipYaw_Roll: {mass: 12.0, offset: [-12.5, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RHipPitch"
      id: 11
      transform: [0, 0, 0]
      rpy: [90, 0, 0]
      mass_offsets:
        #KomplettGelenktMitHalterung: {mass: 194 - 12.0, offset: [10, 0, 30] }
        KomplettGelenktMitHalterung: {mass: 182.0, offset: [10, 0, 30] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RKnee"
      id: 13
      transform: [180, 0, 0]
      rpy: [0, 0, 0]
      mass_offsets:
        MX64: {mass: 140.0, offset: [-10, 0, 0] }
        MetallstückHipPitchKnie: {mass: 54.0, offset: [-90, 0, 2] }
        Kabel: {mass: 4.0, offset: [-90, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RAnklePitch"
      id: 15
      transform: [180, 0, 0]
      rpy: [180, 0, 0]
      mass_offsets:
        MetallstückKnieAnklePitch: {mass: 84.0, offset: [-110, 0, 2] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RAnkleRoll"
      id: 17
      transform: [0, 0, 0]
      #rpy: [90, 0, 0]
      rpy: [-90, 0, 0]
      comment: "the local y-axis is the global x-axis"
      mass_offsets:
        #DoppelMotor: {mass: 194 - 12.0, offset: [-10, -300, 0] }
        DoppelMotor: {mass: 182.0, offset: [-300, 10, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RToe"
      id: 27
      transform: [25, 60, 0]
      rpy: [-90, 0, 0]
      comment: "Liegt 25mm über dem Boden"
      mass_offsets:
        Beispielmasse: {mass: 0.0, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RFootEndpoint"
      id: 34
      transform: [25, 0, 50]
      rpy: [0, -90, 0]
      comment: "the local and global coordinate system are equal"
      mass_offsets:
        MetallHalterung: {mass: 12.0, offset: [0, 0, 7.5] }
        GroßeFußplatte: {mass: 140.0, offset: [30, -20, 0.5] }
      #,def_min_max_angles: [0, 0, 0]

LLeg:
    - name: "BellyRoll"
      id: 29
      transform: [0, 0, -237]
      rpy: [90, 0, -90]
      comment: "Using the left bellyPitch, Ignoring the right one right now, but we mustn't forget it"
      mass_offsets:
        Beispielmasse: {mass: 0.0, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "BellyPitch"
      id: 30
      transform: [15, 0, 0]
      comment: ""
      rpy: [90, 0, 0]
      mass_offsets:
        BellyPitch_RollHalterung: {mass: 34.0, offset: [35, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LHipYaw"
      id: 8
      transform: [60, -80, 0]
      rpy: [-90, 0, -90]
      comment: "the y-axis is the negative global z-axis, local x-axis is the negative global"
      mass_offsets:
        #HalbeBellyRollHipPitchKonstruktion: {mass: (338 - 140) / 2.0, offset: [-35, 0, 0] }
        HalbeBellyRollHipPitchKonstruktion: {mass: 99.0, offset: [0, -45, 0] }
        #HalberMX64Anteil: {mass: 140 / 2.0, offset: [-15, 0, 0] }
        HalberMX64Anteil: {mass: 70.0, offset: [0, -65, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LHipRoll"
      id: 10
      transform: [0, 0, 0]
      rpy: [0, 180, 90]
      comment: "the local y axis is the global negative x-axis and the local x-axis is the global nagative z-axis"
      mass_offsets:
        VerbindugsstückHipYaw_Roll: {mass: 12.0, offset: [-12.5, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LHipPitch"
      id: 12
      transform: [0, 0, 0]
      rpy: [-90, 0, 0]
      mass_offsets:
        #KomplettGelenktMitHalterung: {mass: 194 - 12.0, offset: [10, 0, 30] }
        KomplettGelenktMitHalterung: {mass: 182.0, offset: [10, 0, -30] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LKnee"
      id: 14
      transform: [180, 0, 0]
      rpy: [0, 0, 0]
      mass_offsets:
        MX64: {mass: 140.0, offset: [-10, 0, 0] }
        MetallstückHipPitchKnie: {mass: 54.0, offset: [-90, 0, -2] }
        Kabel: {mass: 4.0, offset: [-90, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LAnklePitch"
      id: 16
      transform: [180, 0, 0]
      rpy: [180, 0, 0]
      mass_offsets:
        MetallstückKnieAnklePitch: {mass: 84.0, offset: [-110, 0, -2] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LAnkleRoll"
      id: 18
      transform: [0, 0, 0]
      rpy: [90, 0, 0]
      comment: "regular joint, local y-axis is the global x-axis"
      mass_offsets:
        #DoppelMotor: {mass: 194 - 12.0, offset: [-10, -30, 0] }
        DoppelMotor: {mass: 182.0, offset: [-10, -30, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LToe"
      id: 28
      transform: [25, 60, 0]
      rpy: [90, 0, 0]
      mass_offsets:
        Beispielmasse: {mass: 0.0, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LFootEndpoint"
      id: 35
      transform: [25, 0, -50]
      rpy: [-90, -90, 90]
      comment: "the local and the global coordinate system are equal"
      mass_offsets:
        MetallHalterung: {mass: 12.0, offset: [0, 0, 7.5] }
        GroßeFußplatte: {mass: 140.0, offset: [30, 20, 0.5] }
      #,def_min_max_angles: [0, 0, 0]
Virtual:
    - name: "RHandRoll"
      id: 21
      transform: [0, 0, 0]
      rpy: [0, 0, 0]
      mass_offsets:
        Beispielmasse: {mass: 0.0, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LHandRoll"
      id: 22
      transform: [0, 0, 0]
      rpy: [0, 0, 0]
      mass_offsets:
        Beispielmasse: {mass: 0.0, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RHandPitch"
      id: 23
      transform: [0, 0, 0]
      rpy: [0, 0, 0]
      mass_offsets:
        Beispielmasse: {mass: 0.0, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "LHandPitch"
      id: 24
      transform: [0, 0, 0]
      rpy: [0, 0, 0]
      mass_offsets:
        Beispielmasse: {mass: 0.0, offset: [0, 0, 0] }
      #,def_min_max_angles: [0, -180, 180]
    - name: "RShoulderYaw"
      id: 25
      transform: [0, 0, 0]
      rpy: [0, 0, 0]
      mass_offsets:
        Beispielmasse: {mass: 0.0, offset: [0, 0, 0]}
    #,def_min_max_angles: [0, -180, 180]
    - name: "LShoulderYaw"
      id: 26
      transform: [0, 0, 0]
      rpy: [0, 0, 0]
      mass_offsets:
        Beispielmasse: {mass: 0.0, offset: [0, 0, 0]}
      #,def_min_max_angles: [0, -180, 180]
