"AutoWhiteBalanceOn": false
"WhiteBalanceTemperature": 127
#255 / 2
"Brigthness": 127
#255 / 2
"FocusAuto": false
"FocusAbsolute": 10
"Gain": 32
"ExposureAuto": true
"ExposureAuto": false
"Contrast": 35
#255 * 14 / 100
